#!/usr/bin/env dash

# TODO: name first client 'main' if not taken

curr_dir() {
    dir="${PWD##*/}"
    dir="$(echo "$dir" | sd -- ' ' '_' | sd -- '\.' '-' | sd -- '-_' '')"
    printf %s "$dir"
}

session="${KAKOUNE_SESSION:-$(curr_dir)}"

exists() {
    target="$1"
    for s in $(kak -l)
    do
        if [ "${target}" = "${s}" ];
        then
            return 0
            break
        fi
    done
    return 1
}

if ! exists "$session"
then
    setsid kak -d -s "${session}" < /dev/null > /dev/null 2>&1 &
    while ! kak -l | rg -q -F -x "${session}"; do
        sleep 0.01
    done
fi

kak -c "$session" "$@"
