#!/usr/bin/env dash

new_session=${PWD##*/}

exists() {
    for session in $(kak -l);
    do
        if [ "${new_session}" = "${session}" ];
        then
            return 0
            break
        fi
    done
    return 1
}

if exists;
then
    kak -c $new_session "$@"
else
    setsid kak -d -s "${new_session}" < /dev/null > /dev/null 2>&1 &
    while ! kak -l | rg -q -F -x "${new_session}"; do
        continue
    done
    kak -c $new_session "$@"
fi
