#!/usr/bin/env bash

dirs=$@
curr="$KITTY_LISTEN_ON"

for dir in $dirs;
do
    listen_on="unix:@kitty-scratch-${dir}"
    kitty --detach --class=__scratchpad --listen-on="$listen_on" --title="$dir"
    echo "spawned new scratch: ${listen_on}"
    #TODO: rg instead
    sleep 0.4
    echo "z ${dir}" | kitty @ --to="$listen_on" send-text --stdin
done

kitty @ --to="$curr" focus-window
