#!/usr/bin/env dash
status=$(media status)
if [ "${status}" = "Playing" ]; then
    media pause
    sleep 1
fi
cvlc "${DOTFILES}/skyrim_quest_update.mp3" --play-and-exit
if [ "${status}" = "Playing" ]; then
    media play
fi
